main_app/urls.py
from django.contrib.auth.views import PasswordChangeDoneView, PasswordChangeView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from .views import MainView, RegistrationView, LoginUserView, LogoutView, ProfileView, ProfileUpdateView, \
    UserPasswordChangeView, UserProfileDetailView

app_name = 'main_app'


urlpatterns = [
    path('', MainView.as_view(), name='main'),
    path('registration/', RegistrationView.as_view(), name='registration'),

    path('logout/', LogoutView.as_view(), name='logout'),
    path('login/', LoginUserView.as_view(), name='login'),

    path('profile/', ProfileView.as_view(), name='profile'),
    path('user-profile/<int:pk>/', UserProfileDetailView.as_view(), name='profile_detail'),
    path('update/', ProfileUpdateView.as_view(), name='update'),

    path('password_change/', UserPasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(template_name='profile/password_change_done.html'), name='password_change_done'),

    path('password_reset/', PasswordResetView.as_view(template_name='profile/password_reset_form.html',
                                                       email_template_name='profile/password_reset_email.html',
                                                       success_url=reverse_lazy('main_app:password_reset_done')), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(template_name='profile/password_reset_done.html'), name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='profile/password_reset_confirm.html',
                                                                                success_url=reverse_lazy('main_app:password_reset_complete')), name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(template_name='profile/password_reset_complete.html'), name='password_reset_complete'),




]

site_fsc/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls', namespace='main_app')),
    path('messages/', include('message_app.urls', namespace='message_app')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/models.py
from django.db import models
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.contrib.auth.models import AbstractUser, PermissionsMixin
from django.utils.translation import gettext_lazy as _


class CustomUserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, first_name, last_name, password, **extra_fields):
        """
        Создание и сохранение пользователя с указанной почтой и паролем.
        """
        if not email:
            raise ValueError(_("Email must be provided"))
        email = self.normalize_email(email)
        user = self.model(email=email, first_name=first_name, last_name=last_name, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, first_name, last_name, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, first_name, last_name, password, **extra_fields)

    def create_superuser(self, email, first_name, last_name, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_("Superuser must have is_staff=True."))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_("Superuser must have is_superuser=True."))

        return self._create_user(email, first_name, last_name, password, **extra_fields)


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(verbose_name=_('Электронная почта'), max_length=255, unique=True)
    first_name = models.CharField(verbose_name=_('Имя'), max_length=150)
    last_name = models.CharField(verbose_name=_('Фамилия'), max_length=150)
    birth_day = models.DateField(verbose_name=_('дата рождения'), null=True, blank=True)
    gender = models.CharField(verbose_name=_('Пол'), max_length=15, choices=[('Мужчина', _('Мужчина')), ('Женищна', _('Женщина'))], blank=True)
    bio = models.TextField(verbose_name=_('О себе'), blank=True)
    location = models.CharField(verbose_name=_('Город'), max_length=100, blank=True)
    avatar = models.ImageField(default='default/default_photo.png', verbose_name=_('Фото профиля'), upload_to='avatars/', null=True, blank=True)
    is_staff = models.BooleanField(verbose_name=_('Доступ к админ-панели'), default=False)
    is_superuser = models.BooleanField(verbose_name=_('Администратор'), default=False)
    is_active = models.BooleanField(verbose_name=_('Активен'), default=True)
    rating = models.PositiveIntegerField(verbose_name=_('Рейтинг'), default=0)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)


    def __str__(self):
        return self.email

    class Meta:
        verbose_name = _('Пользователь')
        verbose_name_plural = _('Пользователи')
        ordering = ['email']

main_app/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm
from django.utils.translation import gettext_lazy as _
from . models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(label='Электронная почта', widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput(attrs={'class': 'form-control'}))


    class Meta:
        model = get_user_model()
        fields = ('first_name', 'last_name', 'email', 'password1', 'password2', 'birth_day', 'gender', 'bio', 'location', 'avatar')
        labels = {
            'first_name': _('Имя'),
            'last_name': _('Фамилия'),
            'birth_day': _('Дата рождения'),
            'gender': _('Пол'),
            'bio': _('О себе'),
            'location': _('Город'),
            'avatar': _('Фото профиля'),
            'password1': _('Пароль'),
            'password2': _('Повторите пароль'),
        }

        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'birth_day': forms.DateInput(attrs={'class': 'form-control'}),
            'gender': forms.Select(attrs={'class': 'form-control'}),
            'bio': forms.Textarea(attrs={'class': 'form-control'}),
            'location': forms.TextInput(attrs={'class': 'form-control'}),
            'avatar': forms.FileInput(attrs={'class': 'form-control'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
        }

        def clean_email(self):
            email = self.cleaned_data['email']
            if get_user_model.objects.filter(email=email).exists():
                raise forms.ValidationError(_("Пользователь с таким email уже существует."))
            return email


class LoginForm(AuthenticationForm):
    # email = forms.EmailField(label='Электронная почта', widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = get_user_model()
        fields = ('email', 'password')


class ProfileUpdateForm(forms.ModelForm):
    email = forms.EmailField(disabled=True, label='Электронная почта', widget=forms.EmailInput(attrs={'class': 'form-control'}))

    class Meta:
        model = get_user_model()
        fields = ('first_name', 'last_name', 'email', 'birth_day', 'gender', 'bio', 'location', 'avatar')
        labels = {
            'first_name': _('Имя'),
            'last_name': _('Фамилия'),
            'birth_day': _('Дата рождения'),
            'gender': _('Пол'),
            'bio': _('О себе'),
            'location': _('Город'),
            'avatar': _('Фото профиля'),
            'email': _('Электронная почта'),
        }
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'birth_day': forms.DateInput(attrs={'class': 'form-control'}),
            'gender': forms.Select(attrs={'class': 'form-control'}),
            'bio': forms.Textarea(attrs={'class': 'form-control'}),
            'location': forms.TextInput(attrs={'class': 'form-control'}),
            'avatar': forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
        }


class UserPasswordChangeForm(PasswordChangeForm):
    class Meta:
        model = get_user_model()
        fields = ['old_password', 'new_password1', 'new_password2']
        widgets = {
            'old_password': forms.PasswordInput(attrs={'class': 'form-control'}),
            'new_password1': forms.PasswordInput(attrs={'class': 'form-control'}),
            'new_password2': forms.PasswordInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'old_password': _('Старый пароль'),
            'new_password1': _('Новый пароль'),
            'new_password2': _('Повторите новый пароль'),
        }

main_app/views.py
from django.contrib.auth import logout, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, ListView, DetailView, UpdateView
from . models import CustomUser
from .forms import CustomUserCreationForm, LoginForm, ProfileUpdateForm, UserPasswordChangeForm




class MainView(LoginRequiredMixin, ListView):
    """Функция для отображения главной страницы"""
    model = get_user_model()
    template_name = 'main.html'
    context_object_name = 'users'
    extra_context = {'title': 'Главная страница'}


class RegistrationView(CreateView):
    """Функция для регистрации пользователя"""
    form_class = CustomUserCreationForm
    template_name = 'registration/registration.html'
    extra_context = {'title': 'Регистрация пользователя'}

    def get_success_url(self):
        return reverse_lazy('main_app:login')


class LoginUserView(LoginView):
    form_class = LoginForm
    template_name = 'registration/login.html'
    extra_context = {'title': 'Авторизация пользователя'}


class LogoutView(LoginRequiredMixin, View):
    """Функция для выхода пользователя с сайта"""
    def get(self, request):
        return render(request, 'registration/logout.html')


    def post(self, request):
        logout(request)
        return redirect('main_app:login')


class ProfileView(LoginRequiredMixin, DetailView):
    """Функция для просмотра профиля пользователя"""
    model = get_user_model()
    template_name = 'profile/profile.html'
    extra_context = {'title': 'Профиль пользователя'}


    def get_object(self, *args, **kwargs):
        return self.request.user


class UserProfileDetailView(LoginRequiredMixin, DetailView):
    """Функция для просмотра профиля пользователя по его id"""
    model = get_user_model()
    template_name = 'profile/profile_detail.html'
    extra_context = {'title': 'Профиль пользователя'}
    context_object_name = 'user_profile'


class UserPasswordChangeView(LoginRequiredMixin, PasswordChangeView):
    form_class = UserPasswordChangeForm
    template_name = 'profile/password_change.html'
    success_url = reverse_lazy('main_app:password_change_done')
    extra_context = {'title': 'Изменение пароля пользователя'}




class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = ProfileUpdateForm
    template_name = 'profile/update.html'
    extra_context = {'title': 'Редактирование профиля пользователя'}

    def get_success_url(self):
        return reverse_lazy('main_app:profile')


    def get_object(self, *args, **kwargs):
        return self.request.user


class UserPasswordChangeView(LoginRequiredMixin, PasswordChangeView):
    form_class = UserPasswordChangeForm
    template_name = 'profile/password_change.html'
    success_url = reverse_lazy('main_app:password_change_done')
    extra_context = {'title': 'Изменение пароля пользователя'}

main_app/templates/profile/password_change.html
{% extends "main.html" %}

{% block content %}
<h1>Изменение пароля</h1>

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Сохранить изменения</button>
  {% if form.errors %}
  <p class="error">Пароль должен содержать как минимум 8 символов и быть уникальным.</p>
  {% endif %}
  {% if form.non_field_errors %}
  <p class="error">{{ form.non_field_errors }}</p>
  {% endif %}
</form>
{% endblock %}

main_app/templates/profile/password_change_done.html
{% extends "main.html" %}

{% block content %}
<h1>Пароль успешно изменен!</h1>

<p><a href="{% url 'main_app:profile' %}">Вернуться на страницу профиля</a></p>
{% endblock %}

main_app/templates/profile/password_reset_complete.html
{% extends "main.html" %}


{% block content %}
<h1> Пароль успешно изменен</h1>

<h1>Поздравляем, вы успешно изменили пароль</h1>
<a href="{% url 'main_app:login' %}">Войти</a>
{% endblock %}

main_app/templates/profile/password_reset_confirm.html
{% extends "main.html" %}



{% block content %}
<h1>Новый пароль</h1>
<form method="post">
  {% csrf_token %}
  <div class="form-error">{{form.non_field_errors}}</div>
  {% for field in form %}
  <p><label class="form-label" for="{{field.id_for_label}}">{{field.label}}:</label>{{field}}</p>
  <div class="form-error">{{field.errors}}</div>
  {% endfor %}

  <p><button type="submit">Сохранить</button></p>
</form>

{% endblock %}

main_app/templates/profile/password_reset_done.html
{% extends 'main.html' %}
{% load i18n %}


<div class="breadcrumbs">
<p><h1>Сброс пароля</h1>


<p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>

<p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>

main_app/templates/profile/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'main_app:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'In case you’ve forgotten, you are:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

main_app/templates/profile/password_reset_form.html
{% extends 'main.html' %}

{% block content %}
<h1>Восстановление пароля</h1>
<form method="post">
  {% csrf_token %}
  {% for field in form %}
  <p><label class="form-label" for="{{field.id_for_label}}">{{field.label}}:</label>{{field}}</p>
  <div class="form-error">{{field.errors}}</div>
  {% endfor %}
  <button type="submit">Восстановить через e-mail</button>
</form>
{% endblock %}

main_app/templates/profile/profile.html
{% extends 'main.html' %}

{% block content %}
<center>
    {% if user.is_authenticated %}
        {% if user.avatar %}
    <p><img src="{{ user.avatar.url }}" width="200" height="200"></p>
        {% else %}
        <p><img src="{{ default_photo }}" width="200" height="200"></p>
        {% endif %}
    <p>Имя:{{ user.first_name }}</p>
    <p>Фамилия:{{ user.last_name }}</p>
    <p>Дата рождения:{{ user.birth_day }}</p>
    <p>Пол:{{ user.gender }}</p>
    <p>О себе:{{ user.bio }}</p>
    <p>Город:{{ user.location }}</p>
    {% else %}
    <a href="{% url 'main_app:login' %}">Войти</a>
    <a href="{% url 'main_app:register' %}">Зарегистрироваться</a>
    {% endif %}



<a href="{% url 'main_app:update' %}">Изменить данные</a>
</center>
{% endblock %}

main_app/templates/profile/profile_detail.html
{% extends 'main.html' %}

{% block content %}
<center>
<p><h1>Профиль пользователя</h1></p>

<p><img src="{{user_profile.avatar.url}}" width="200" height="200"></p>


<p>Имя:{{user_profile.first_name}}</p>
<p>Фамилия:{{user_profile.last_name}}</p>
<p>Дата рождения:{{user_profile.birth_day}}</p>
<p>Пол:{{user_profile.gender}}</p>
<p>О себе:{{user_profile.bio}}</p>
<p>Город:{{user_profile.location}}</p>
    <a href="#">Написать сообщение</a>
</center>

{% endblock %}

main_app/templates/profile/update.html
{% extends 'main.html' %}

{% block content %}
<form method="post" enctype="multipart/form-data" action="{% url 'main_app:update' %}">
  {% csrf_token %}
  <div class="form-error">{{ form.non_field_errors }}</div>
  {% for f in form %}
  <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}:</label> {{ f }}</p>
  <div class="form-error">{{ f.errors }}</div>
  {% endfor %}
  <button type="submit">Сохранить изменения</button>
</form>
{% endblock %}